
tutorial.client.duration=10000


spring.application.name=pedido-api
# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html
spring-doc.packages-to-scan[]=com.kido.pedido_api.controller

server.port=7788

rabbitmq.exchange.name=pedidos.v1.pedido-criado

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=rabbitmq
spring.rabbitmq.password=rabbitmq

