server:
  port: 8888
spring:
  application:
    name: k1do-config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/K1dou/k1dou-config-server.git"
          #username:
          #password:
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
          search-paths: config-repository



encrypt:
  key: "Marcelo2809@"